name = "Wall"

[in]
grid = { size = "4:4", offset = "4:12" }

[in.pieces]
# Variant 1
tl1 = "0:0 4:4  0:0 " # Top-left
t1  = "1:0 8:4  4:0 " # Top
tr1 = "3:0 4:4 12:0 " # Top-right
l1  = "0:1 4:8  0:4 " # Left
c1  = "1:1 8:8  4:4 " # Center
r1  = "3:1 4:8 12:4 " # Right
bl1 = "0:3 4:4  0:12" # Bottom-left
b1  = "1:3 8:4  4:12" # Bottom
br1 = "3:3 4:4 12:12" # Bottom-right
# Variant 2
tl2 = "6:0 4:4  0:0 "
t2  = "7:0 8:4  4:0 "
tr2 = "9:0 4:4 12:0 "
l2  = "6:1 4:8  0:4 "
c2  = "7:1 8:8  4:4 "
r2  = "9:1 4:8 12:4 "
bl2 = "6:3 4:4  0:12"
b2  = "7:3 8:4  4:12"
br2 = "9:3 4:4 12:12"
# Variant 3
tl3 = "12:0 4:4  0:0 "
t3  = "13:0 8:4  4:0 "
tr3 = "15:0 4:4 12:0 "
l3  = "12:1 4:8  0:4 "
c3  = "13:1 8:8  4:4 "
r3  = "15:1 4:8 12:4 "
bl3 = "12:3 4:4  0:12"
b3  = "13:3 8:4  4:12"
br3 = "15:3 4:4 12:12"

[out]
size = "234:90"
grid = { size = "18:18" }
scale = 2.0

[out.placements]

# Top-Left
"0:3" = "tl1 t1 l1 c1"
"2:3" = "tl2 t2 l2 c2"
"4:3" = "tl3 t3 l3 c3"

# Top
"1:0" = "t1 c1"
"2:0" = "t2 c2"
"3:0" = "t3 c3"

# Top-Right
"1:3" = "t1 tr1 c1 r1"
"3:3" = "t2 tr2 c2 r2"
"5:3" = "t3 tr3 c3 r3"

# Left
"0:0" = "l1 c1"
"0:1" = "l2 c2"
"0:2" = "l3 c3"

# Center
"1:1" = "c1"
"2:1" = "c2"
"3:1" = "c3"

# Right
"4:0" = "c1 r1"
"4:1" = "c2 r2"
"4:2" = "c3 r3"

# Bottom-Left
"0:4" = "l1 c1 bl1 b1"
"2:4" = "l2 c2 bl2 b2"
"4:4" = "l3 c3 bl3 b3"

# Bottom
"1:2" = "c1 b1"
"2:2" = "c2 b2"
"3:2" = "c3 b3"

# Bottom-Right
"1:4" = "c1 r1 b1 br1"
"3:4" = "c2 r2 b2 br2"
"5:4" = "c3 r3 b3 br3"

# Lone Tile
"9:3" = "tl1 t1 tr1 l1 c1 r1 bl1 b1 br1"
"10:3" = "tl2 t2 tr2 l2 c2 r2 bl2 b2 br2"
"11:3" = "tl3 t3 tr3 l3 c3 r3 bl3 b3 br3"

# Row
"6:4" = "t1 c1 b1"
"7:4" = "t2 c2 b2"
"8:4" = "t3 c3 b3"

# Column
"5:0" = "l1 c1 r1"
"5:1" = "l2 c2 r2"
"5:2" = "l3 c3 r3"

# Cap::Top
"6:0" = "tl1 t1 tr1 l1 c1 r1"
"7:0" = "tl2 t2 tr2 l2 c2 r2"
"8:0" = "tl3 t3 tr3 l3 c3 r3"
"6:1" = "c1"
"7:1" = "c2"
"8:1" = "c3"

# Cap::Bottom
"6:3" = "l1 c1 r1 bl1 b1 br1"
"7:3" = "l2 c2 r2 bl2 b2 br2"
"8:3" = "l3 c3 r3 bl3 b3 br3"
"6:2" = "c1"
"7:2" = "c2"
"8:2" = "c3"

# Cap::Left
"9:0" = "tl1 t1 l1 c1 bl1 b1"
"9:1" = "tl2 t2 l2 c2 bl2 b2"
"9:2" = "tl3 t3 l3 c3 bl3 b3"
"10:0" = "c1"
"10:1" = "c2"
"10:2" = "c3"

# Cap::Right
"12:0" = "t1 tr1 c1 r1 b1 br1"
"12:1" = "t2 tr2 c2 r2 b2 br2"
"12:2" = "t3 tr3 c3 r3 b3 br3"
"11:0" = "c1"
"11:1" = "c2"
"11:2" = "c3"
